#!/bin/bash

### [ DEPENDENCIES ] ###
source utility/checks
source utility/operations

### [##############] ###

## Checks
# 0.1.Check whether there are uncommitted changes, exit 1
checkUncommittedChanges

# 1. align your local master to the orgin one
updateLocalMaster

# 23, 142 etc.
hotfixNumber=$1

# 1.1. establish current Git branch and define variables
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
devBranch=develop
masterBranch=master
releaseBranch=hotfix-$hotfixNumber
 
# 2. create the release branch from the master branch
echo Creating branch named hotfix-$1 from master branch..
git checkout -b $releaseBranch $masterBranch

echo Currently on branch hotfix-$1, you can now work at the fix