#!/bin/bash

### [ DEPENDENCIES ] ###
source .utility/checks

### [##############] ###

## Checks
# 1.Check whether there are uncommitted changes, exit 1
check-uncommited-changes

# 23, 142 etc.
hotfixNumber=$1

# establish current Git branch and define variables
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
devBranch=develop
masterBranch=master
releaseBranch=hotfix-$hotfixNumber
 
# create the release branch from the master branch
echo Creating branch named hotfix-$1 from master branch..
git checkout -b $releaseBranch $masterBranch

echo Currently on branch hotfix-$1, you can now work at the fix
