#!/bin/bash

## Checks
# 1.Check whether there are uncommitted changes, exit 1
if ! git diff-index --quiet HEAD --; then
	echo "There are uncommited changes, commit or stash them before you use this script"
	exit 1
fi

# 23, 142 etc.
hotfixNumber=$1

# establish current Git branch and define variables
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
devBranch=develop
masterBranch=master
releaseBranch=hotfix-$hotfixNumber
 
# create the release branch from the master branch
echo Creating branch named hotfix-$1 from master branch..
git checkout -b $releaseBranch $masterBranch

echo Currently on branch hotfix-$1, you can now work at the fix
