#!/bin/bash

# 23, 142 etc.
hotfixNumber=$1

#check whether there are uncommitted changes
#TODO

# establish branch and tag name variables
# current Git branch
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
devBranch=develop
masterBranch=master
releaseBranch=hotfix-$hotfixNumber
 
# create the release branch from the master branch
echo Creating branch named hotfix-$1 from master branch..
git checkout -b $releaseBranch $masterBranch

echo Currently on branch hotfix-$1, you can now work at the fix
