#!/bin/bash

function checkUncommittedChanges {
	if ! git diff-index --quiet HEAD --; then
		log "There are uncommited changes: commit or stash them before you continue"
		exit 1
	fi
    log "No changes found"
}

# Remote exists - Exit script if remote does not exist
function checkOriginExists {
    git ls-remote --exit-code ${remote} >/dev/null 2>&1
    if [ $? -ne 0 ]
    then
        log "Remote ${remote} does not exist"
        exit 1
    fi
}

#Check we are in a git repo
function checkGitRepo(){
    git status >/dev/null 2>&1 || { log "Error: You're not in a git repository."; exit 1; } 
}

# Root path of Repo
function getRepoPath(){
    checkGitRepo
    return git rev-parse --show-toplevel
}
#rootpath=$(git rev-parse --show-toplevel)

function(){
    git diff --exit-code
}

function checkBranchNameIsOk() {

}