#! bin/bash

RED='\033[0;31m'
BLUE='\033[34m'
PURPLE='\033[35m'
YELLOW='\033[33m'

NC='\033[0m' # No Color

#printf "I ${RED}love${NC} Stack Overflow\n"

# Basic log function, "=====> " print standard information
function log(){
    printf "\033[34m [ $(date +"%D %T") ] ===>\033[1m\033[35m $1 \033[0m\n"
}

function info(){
    printf "\033[34m [ $(date +"%D %T") ] \033[1m\033[32m $1 \033[0m\n"
}