#!/bin/bash

### [ DEPENDENCIES ] ###
source lib/checks
source lib/operations
source lib/colored_logger

### [##############] ###

usage()
{
    echo
    echo "Usage: zz <script-name> <script-parameter>"
    echo "  hotifx-setup:"
    echo "    - prepares a branch from master to commit the the fix"
    echo "      on."       
    echo "  hotifx-push:"
    echo "    - pushes the fix on master branch, rebasing develop"
}

# 1. Check whether the user is calling the script properly,
# if it's not the case, print the help
# Usage example:
# es1. zz hotfix-setup 76
# es2. zz hotfix-push 76
# first argument $1: script to call
# second argument $2: parameter for the selected script

#VARIABLES#
scriptName=$1
scriptFirstParameter=$2

#check for null inputs
if [ -z "$1" || -z "$2" ]; then
    log "Values passed to the script cannot be null!"
    usage
    exit 1
fi

#call the right script and pass the $2 argument
case $1 in
    hotfix-setup )
        sh hotfix-setup $2
        exit 0
        ;;
    hotfix-push )
        sh hotfix-push $2
        exit 0
        ;;
    help )
        usage
        exit 0
        ;;
    * )
        log "Error: You didn't specify a script name, please type zz help to print the usage"
        exit 1
        ;;
esac